# Config File for Compass Update Utility
paths:
  CompassUpdatePath: /Users/bernie/PycharmProjects/compass_updater/Updates/Compass/
  CompassLicenseUpdatePath: /Users/bernie/PycharmProjects/compass_updater/Updates/Lizenzstecker/