# Config File for Compass Update Utility
paths:
  CompassUpdatePath: C:\Users\bernie\PycharmProjects\compass_updater/Updates/Compass/
  CompassLicenseUpdatePath: C:\Users\bernie\PycharmProjects\compass_updater/Updates/Lizenstecker/